### ISSUE TITLE
Recently, it does not accept or reject any password

### ISSUE THREAD

**Issue by SparkDustJoe** [Sneezry/authenticator#33]
When I enter my password and hit enter or OK, there is no feedback that I was entering the correct or incorrect password, the input box just clears my input as if the pop-up had just come up.  I see all my accounts are still there but "Encrypted" but I can't get to them if it doesn't accept my password.  I have cleared my cookies and history, restarted my computer, removed all other extensions to see if any are interfering (which they shouldn't in Chrome), but no luck.

**Comment by Sneezry** [comment]
Hi @SparkDustJoe, sorry about that. Can you see a box says 'Some accounts and passphrase do not match.' after you enter password and click OK?

**Comment by SparkDustJoe** [comment]
No visual indicators of any kind.
The input box merely empties out with no explanation or feedback no matter
what password was entered, right or wrong.

**Comment by Sneezry** [comment]
Please do as follow, and tell me what you can see:

1/ Click the extension icon to open popup page
2/ Right click anywhere on popup page and select *Inspect element*
3/ Click *Console* tab in Developer Tools(the last tab on the top of the window)
4/ Move your mouse back to popup page and enter password then hit *OK*

If the extension went wrong, you should see some red code in Developer Tools window, can you something in red? If so, please paste anything you can see here, thanks.

**Comment by SparkDustJoe** [comment]
_*When I just inspect the element without doing anything first*_
`Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.jsSHA.getHMAC (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/jssha-1.31.min.js:11:14553)
    at generate (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/totp.js:71:22)
    at updateCode (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:545:62)
    at Object.showCodes [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:678:9)
    at chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:66:21handler @ extensions::uncaught_exception_handler:8
extensions::uncaught_exception_handler:8 Error in response to storage.get: Type`

_*And then when I actually try to input a passphrase*_
`Error: Cannot read property 'length' of undefined
    at Object.jsSHA.getHMAC (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/jssha-1.31.min.js:11:14553)
    at generate (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/totp.js:71:22)
    at updateCode (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:545:62)
    at showCodes (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:678:9)
    at Object.callback (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:846:9)
    at encryptSecret (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:797:25)
    at HTMLInputElement.document.getElementById.onkeydown (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:146:9) `

**Comment by SparkDustJoe** [comment]
Hope this helps...

**Comment by SparkDustJoe** [comment]
Perhaps updating the jsSHA library to the latest version and retesting would help?  https://github.com/Caligatio/jsSHA

**Comment by Sneezry** [comment]
Hi @SparkDustJoe , sorry I didn't reply you in time.

It seems there is something wrong with `chrome.storage.sync.get` which is a native method of Chrome. Can you see something in Export/Import box from menu?

**Comment by SparkDustJoe** [comment]
I will look at this when I'm in front of the affected machine.  Do you want me to see if it just pops up the box that asks me to import or export my settings, or do you want me to actually test importing and exporting?

**Comment by Sneezry** [comment]
I wanna check whether you can see data in export/import box so that I can confirm whether the issue is caused by `chrome.storage.sync.get` or the data itself.

**Comment by SparkDustJoe** [comment]
It does seem to pull the accounts into what looks like JSON, so it is retrieving them (in encrypted format).  And in fact I should export them for safe keeping anyways.

**Comment by SparkDustJoe** [comment]
![image](https://cloud.githubusercontent.com/assets/9010072/11161998/391c4858-8a5c-11e5-9758-9274aff6c672.png)

Notice how the last account shows  * * * * * *  instead of Encrypted.  They should ALL be encrypted to the same phrase.  That seems odd.  The JSON shows all as "encrypted":true

{"0ddb7ca3e5c2b7743b7f0ba16e4ae6e4":{"account":"REDACTED","encrypted":true,"index":0,"issuer":"","secret":"REDACTED","type":"totp"},
"0f2cac3d73d1a58c4da6bc19045ecb2f":{"account":"REDACTED","encrypted":true,"index":6,"issuer":"","secret":"REDACTED","type":"totp"},
"287ce6e5180072176653a321f46f7e57":{"account":"REDACTED","encrypted":true,"index":4,"issuer":"","secret":"REDACTED","type":"totp"},
"2c55c2d87ff899a3b20c30bc6bcc3201":{"account":"REDACTED","encrypted":true,"index":2,"issuer":"","secret":"REDACTED","type":"totp"},
"3e60e40e2411b7554af52c887d6d533c":{"account":"REDACTED","encrypted":true,"index":8,"issuer":"","secret":"REDACTED","type":"totp"},
"673420270bfebf31e0d33996a8aa0014":{"account":"DOTDOTDOT","encrypted":true,"index":9,"issuer":"NOTBLANK","secret":"REDACTED","type":"totp"},
"a99d6315b20b2255291f1e9ec506d3c1":{"account":"REDACTED","encrypted":true,"index":7,"issuer":"","secret":"REDACTED","type":"totp"},
"f10fe78783f76c21a01351fd42af0eb6":{"account":"REDACTED","encrypted":true,"index":1,"issuer":"","secret":"REDACTED","type":"totp"},
"f1f382edc9dc6d655fa2c7d2cdefd5b8":{"account":"REDACTED","encrypted":true,"index":3,"issuer":"","secret":"REDACTED","type":"totp"},
"ff5d17fa8cf654d367a08d41f6a2fcb8":{"account":"REDACTED","encrypted":true,"index":5,"issuer":"","secret":"REDACTED","type":"totp"}}

**Comment by SparkDustJoe** [comment]
When I remove that last account, I am getting prompts again, but now none of my accounts will decrypt, so they are locked and potentially lost.
![image](https://cloud.githubusercontent.com/assets/9010072/11162070/6db8af96-8a5e-11e5-8121-250f58860365.png)

**Comment by Sneezry** [comment]
I guess the last account secret has illegal format, maybe I need improve the code to reject accepting it. But I do not think this issue may break your passphrase, it's strange...

**Comment by photonicpr** [comment]
Hey there, this has happened to me as well. My passphrase is correct but it isn't letting me in - all are encrypted. I don't want to delete the extension as this it is very good.

**Comment by Sneezry** [comment]
Hi @photonicpr @SparkDustJoe , I have already started to work on tracking the passphrase issue(https://github.com/Sneezry/authenticator/tree/DO_NOT_USE_THIS_BRANCH), however, I need more test to make the issue reappear.

Zhe Li

**Comment by photonicpr** [comment]
Thank you for looking into this Zhe, talk soon.

Avi


*mobile*: 250-516-1406
*office*: 917-472-9896
*skype*: avi.lambert

**Comment by photonicpr** [comment]
Sneezy, any update on progress to de-encrypt or fix the encryption problems with your chrome app?

**Comment by saingnhansath** [comment]
Hi Sneezry. I have used authenticator with my account mmmglobal. Accidentally the autheticator app become disappear from my computer. When I restore then I lose the code. Could you show me how to back up my code?

**Comment by kardinal23** [comment]
I have the same problems

here you can see what I have in console

popup.html:1 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at jsSHA.getHMAC (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/jssha-1.31.min.js:11:14553)
    at generate (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/totp.js:71:22)
    at updateCode (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:545:62)
    at Object.showCodes [as callback] (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:678:9)
    at chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:66:21
7popup.html:1 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at jsSHA.getHMAC (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/jssha-1.31.min.js:11:14553)
    at generate (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/totp/totp.js:71:22)
    at updateCode (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:545:62)
    at showCodes (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:678:9)
    at Object.callback (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:846:9)
    at encryptSecret (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:797:25)
    at HTMLDivElement.document.getElementById.onclick (chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/javascript/popup.js:124:9)

**Comment by kardinal23** [comment]
Please could you make some instructions what to do? Despite I put correct password I dont see anything
I have to use app from mobile phone
I hope I dont loose it too otherwise I get angry since i need it many times a day for different websites

**Comment by kardinal23** [comment]
what is the right way of updating the jsSHA library to the latest version and retesting ? https://github.com/Caligatio/jsSHA

I downloaded it and it is a console for creating or publish project on GitHub
